<?php
return array(
    '' => 'index/index',
    'sign_in' => 'index/SignIn',
    'sign_up' => 'index/SignUp',
    'create_user' => 'user/SaveUser',
    'authentication' => 'user/Authentication',
    'save_project' => 'project/SaveProject',
    'show_all_projects' => 'project/ShowProjects',
    'delete_project' => 'project/DeleteProject',
    'get_project' => 'project/GetProject',
    'update_project' => 'project/UpdateProject',
    'get_tasks' => 'task/GetTasks',
    'set_done' => 'task/SetDone',
    'delete_tasks' => 'task/DeleteTasks',
    'delete_task' => 'task/DeleteTask',
    'add_task' => 'task/AddTask',
    'get_task' => 'task/GetTask',
    'update_task' => 'task/UpdateTask',
    'logout' => 'logout/GoodBye',
);
